### ISSUE TITLE
Npm module is not properly configured

### ISSUE THREAD

**Issue by felixgirault** [nico3333fr/jquery-accessible-autocomplete-list-aria#11]
Hi,

I just installed your plugin through npm, but I couldn't import it correctly.

The problem seems to arise because there is no `main` field in `package.json`, pointing to the dist file.

Also, there is a little typo in the dist file : `jquery-accessible-autocomplet-list-aria.js` instead of `jquery-accessible-autocomplet[e]-list-aria.js` ;)

**Comment by nico3333fr** [comment]
Hi @felixgirault 

thanks for pointing this out, my mistake, sorry. I've fixed it and updated URL at the same time.

The fix is published on NPM.

Thanks a lot !

**Comment by felixgirault** [comment]
Wow, that was quick!

Thank you :)
