### ISSUE TITLE
Searching from beginning with case sensitivity off populates incorrect suggestions

### ISSUE THREAD

**Issue by Kataract** [nico3333fr/jquery-accessible-autocomplete-list-aria#12]
I used the example code from the README, and added `data-combobox-case-sensitive="no"` and `data-combobox-search-option="beginning"`:

```
<input type="text" name="mysuper_field" id="id_mysuper_field" class="js-combobox" list="beers" data-combobox-prefix-class="combobox" data-combobox-case-sensitive="no" data-combobox-search-option="beginning"/>
  <datalist id="beers">
    <option value="Meteor">
    <option value="Pils">
    <option value="Kronenbourg">
    <option value="Kronenbourg 2 (for test)">
    <option value="Kronenbourg 3 (for test)">
    <option value="Grimbergen">
  </datalist>
```

Searching for "b" should provide no suggestions but gives Grimbergen and the 3 Kronenbourg options as suggestions.  This works fine with case sensitivity left as the default (on), but for my use case I need to have it off.

It looks like the issue is in the big conditional that splits for `containing`/`beginning` - since the `containing` section evaluates to true (it winds up as `false && (false) || (true)`), it doesn't matter that the correct end of the conditional found no results.

**Comment by nico3333fr** [comment]
Hi @Kataract 

you're right, I manage to reproduce it, my parenthesis are not well made. 

I'm going to fix it in a few minutes...

**Comment by nico3333fr** [comment]
Hi again @Kataract ,

this is fixed with last commit https://github.com/nico3333fr/jquery-accessible-autocomplete-list-aria/commit/c4c59e1b54df78a022be2894dce7676d9d515c7e (also updated 

Thanks a lot for finding and reporting this issue 👍
