### ISSUE TITLE
Plural for data-suggestion-word

### ISSUE THREAD

**Issue by acespace90** [nico3333fr/jquery-accessible-autocomplete-list-aria#15]
Hi, is there a way to set the plural of `data-suggestion-word`?
There are some languages (eg: Italian) that use "**Suggerimento**" for the singular, and "**Suggerimenti**" for the plural. 
Can I set the plural suggestion word via `data-*`? 

Actually the plugin adds the "_**s**_" word at the end of the suggestion word, this works for English language but not for other languages.

Thanks

**Comment by nico3333fr** [comment]
Hi @acespace90 ,

good idea, I've implemented it in https://github.com/nico3333fr/jquery-accessible-autocomplete-list-aria/commit/7ee199e560775d02f40657c571cdf7597190f5bb ;)

Thanks a lot ;)

**Comment by acespace90** [comment]
Great, you rock man! :-)

**Comment by acespace90** [comment]
One thing: I can not update to the latest version via npm? 
I'm trying with `npm update jquery-accessible-autocomplete-list-aria` but the version still remains to 1.5.7 and not upgrade to 1.6.0
Where am I wrong?

**Comment by nico3333fr** [comment]
No, you're not wrong, I forgot to publish. I've updated it right now.
