### ISSUE TITLE
In 'no tab' mode, selected option disappears after tabbing to 'clear' button

### ISSUE THREAD

**Issue by sophieschuermans** [nico3333fr/jquery-accessible-autocomplete-list-aria#3]
In the second example using the 'no tab' mode, there seems to be an issue selecting an option with the keyboard (In Firefox, IE11 and Chrome).  When selecting an option with arrow down, I loose the selection after tabbing away to the Clear button. 
1st scenario : I type 'Cr', then I select 'Croissant au chocolat' with the arrow keys, then I hit TAB. I end up on the 'clear' button and the input only contains 'Cr'. I expect that tabbing away from the list confirms my selection as it would in a select. 
2nd scenario : I type 'Cr', then I select 'Croissant au chocolat' with the arrow keys, I hit ENTER. The focus moves to the input which contains 'Croissant au chocolat'. Then I hit TAB. I end up on the 'clear' button and the input only contains 'Cr'. I don't expect my input to disappear when tabbing away.

**Comment by nico3333fr** [comment]
Thanks a lot for pointing out this problem :)
