### ISSUE TITLE
MinLength attribute for search

### ISSUE THREAD

**Issue by rodricifuentes1** [nico3333fr/jquery-accessible-autocomplete-list-aria#4]
Hello Nicolas
First of all thank you for your awesome work.

How can I customize the plugin to enable a minLength attribute?

Thanks

**Comment by nico3333fr** [comment]
Hello @rodricifuentes1 !

> First of all thank you for your awesome work.

You're welcomed. :+1: 

> How can I customize the plugin to enable a minLength attribute?

No need to, I've added the option ;) 

You can adjust the new parameter min_length to enable this feature (see https://github.com/nico3333fr/jquery-accessible-autocomplete-list-aria/commit/e22b93a164ceb41d981727d7290ea28b6e8cb674) or via data-combobox-min-length="xx" on the input if you prefer.

Thanks for your suggestion, and have a nice evening,
Nicolas
